# Generated by BoostInstall.cmake for boost_vmd-1.84.0

include(CMakeFindDependencyMacro)

if(NOT boost_preprocessor_FOUND)
  find_dependency(boost_preprocessor 1.84.0 EXACT)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/boost_vmd-targets.cmake")
